version: "3"

services:
  app:
    build: ./docker/app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d/
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    
volumes:
  db-store:
